---
# yaml-language-server: $schema=https://schema.blue-build.org/recipe-v1.json
# image will be published to ghcr.io/<user>/<name>
name: horizon
# description will be included in the image's metadata
description: Build Horizon Image.

# the base image to build on top of (FROM) and the version tag to use
base-image: ghcr.io/ublue-os/silverblue-main
image-version: 41 # latest is also supported if you want new updates ASAP

# module configuration, executed in order
# you can include multiple instances of the same module
modules:
  - type: files
    files:
      - source: system
        destination: / # copies files/system/* (* means everything inside it) into your image's root folder /

  - type: rpm-ostree
    install:
      - adcli
      - adw-gtk3-theme
      - bcache-tools
      - borgbackup
      - bootc
      - ddcutil
      - evtest
      - epson-inkjet-printer-escpr
      - epson-inkjet-printer-escpr2
      - fastfetch
      - fish
      - foo2zjs
      - fuse-encfs
      - gcc
      - git
      - git-credential-libsecret
      - hplip
      - krb5-workstation
      - ifuse
      - libimobiledevice
      - libxcrypt-compat
      - libsss_autofs
      - lm_sensors
      - make
      - mesa-libGLU
      - oddjob-mkhomedir
      - opendyslexic-fonts
      - printer-driver-brlaser
      - pulseaudio
      - pulseaudio-utils
      - python3
      - python3-pip
      - samba-dcerpc
      - samba-ldb-ldap-modules
      - samba-winbind-clients
      - samba-winbind-modules
      - samba
      - setools-console
      - sssd-ad
      - sssd-krb5
      - sssd-nfs-idmap
      - stress-ng
      - tailscale
      - tmux
      - usbmuxd
      - wireguard-tools
      - xprop
      - wl-clipboard
      - zsh
      - google-noto-fonts-all
      - gnome-initial-setup
      - gnome-control-center
      - gnome-settings-daemon
      - gnome-software
      - gnome-software-rpm-ostree
      - nautilus
      - gnome-shell-extension-appindicator
      - gnome-shell-extension-blur-my-shell
      - gnome-shell-extension-dash-to-dock
      - libgda
      - libgda-sqlite
      - nautilus-open-any-terminal
      - openssh-askpass
      - simple-scan
      - zenity
      - podman
      - distrobox
    remove:
      # example: removing firefox (in favor of the flatpak)
      # "firefox" is the main package, "firefox-langpacks" is a dependency
      - firefox
      - firefox-langpacks # also remove firefox dependency (not required for all packages, this is a special case)
      - gnome-shell-extension-background-logo

  - type: default-flatpaks
    notify: true # Send notification after install/uninstall is finished (true/false)
    system:
      # If no repo information is specified, Flathub will be used by default
      install:
      - org.mozilla.firefox
      - org.gnome.Loupe
      - org.gnome.Calculator
      - org.gnome.Calendar
      - org.gnome.Characters
      - org.gnome.FileRoller
      - org.gnome.NautilusPreviewer
      - org.gnome.TextEditor
      - io.missioncenter.MissionCenter
      - org.gtk.Gtk3theme.adw-gtk3
      - org.gtk.Gtk3theme.adw-gtk3-dark
      - io.github.dvlv.boxbuddyrs
      - com.github.tchx84.Flatseal
      - com.mattjakeman.ExtensionManager
      - com.github.rafostar.Clapper
      - org.localsend.localsend_app
      remove:
      - org.gnome.eog
    user: {} # Also add Flathub user repo, but no user packages

  - type: signing # this sets up the proper policy & signing files for signed images to work fully

